query RecentlyAired($startDate: Int!, $endDate: Int!) {
  Page(perPage: 50) {
    airingSchedules(airingAt_greater: $startDate, airingAt_lesser: $endDate) {
      media {
        ...media
        mediaListEntry {
          ...mediaListEntry
        }
      }
    }
    pageInfo {
      currentPage
      hasNextPage
    }
  }
}
