query Watching($userId: Int!) {
  MediaListCollection(
    userId: $userId
    type: ANIME
    forceSingleCompletedList: true
    status: CURRENT
  ) {
    lists {
      entries {
        ...mediaListEntry
        media {
          ...media
        }
      }
    }
  }
}
