fragment media on Media {
  id
  siteUrl
  title {
    native
    romaji
    english
    userPreferred
  }
  format
  bannerImage
  coverImage {
    medium
    large
    extraLarge
    color
  }
  episodes
  externalLinks {
    id
    url
    site
  }
  nextAiringEpisode {
    episode
    airingAt
  }
}

fragment mediaListEntry on MediaList {
  id
  progress
  status
}
