mutation SetWatchingStatus($mediaId: Int!, $status: MediaListStatus!) {
  SaveMediaListEntry(mediaId: $mediaId, status: $status) {
    status
  }
}

mutation DeleteFromWatching($mediaListId: Int!) {
  DeleteMediaListEntry(id: $mediaListId) {
    deleted
  }
}

# fragment media on Media {
#   id
#   format
#   episodes
#   nextAiringEpisode {
#     airingAt
#     episode
#   }
#   bannerImage
#   title {
#     english
#     romaji
#     native
#     userPreferred
#   }
#   coverImage {
#     medium
#     large
#     extraLarge
#     color
#   }
#   externalLinks {
#     ...mediaExternalLink
#   }
#   isAdult
#   isLicensed
#   countryOfOrigin
#   format
#   siteUrl
#   mediaListEntry {
#     status
#   }
# }

# fragment mediaExternalLink on MediaExternalLink {
#   id
#   url
#   site
# }
