query Schedule($startDate: Int!, $page: Int!) {
  Page(page: $page, perPage: 50) {
    pageInfo {
      currentPage
      hasNextPage
    }
    airingSchedules(airingAt_greater: $startDate, sort: TIME) {
      id
      episode
      airingAt
      media {
        id
        title {
          native
          romaji
          english
          userPreferred
        }
        format
        bannerImage
        coverImage {
          medium
          large
          extraLarge
          color
        }
        episodes
        mediaListEntry {
          id
          progress
          status
        }
        externalLinks {
          id
          url
          site
        }
      }
    }
  }
}
