on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  run-scripts:
    strategy:
      matrix:
        script: [lint, test]
      fail-fast: false
    name: ${{ matrix.script }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v2
        with:
          node-version: "lts/*"
          cache: pnpm
      - run: pnpm i
      - run: npm run ${{ matrix.script }}

      - name: Upload artifacts
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: artifacts
          path: artifacts/
